"""init

Revision ID: 03531c04956a
Revises:
Create Date: 2025-11-21 10:44:06.613512

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "03531c04956a"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "teams",
        sa.Column("team_name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("team_name"),
    )
    op.create_index(op.f("ix_teams_team_name"), "teams", ["team_name"], unique=False)
    op.create_table(
        "users",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("team_name", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["team_name"],
            ["teams.team_name"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_index(op.f("ix_users_user_id"), "users", ["user_id"], unique=False)
    op.create_table(
        "pull_requests",
        sa.Column("pull_request_id", sa.String(), nullable=False),
        sa.Column("pull_request_name", sa.String(), nullable=False),
        sa.Column("author_id", sa.String(), nullable=False),
        sa.Column("status", sa.Enum("OPEN", "MERGED", name="prstatus"), nullable=False),
        sa.Column("assigned_reviewers", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("merged_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("pull_request_id"),
    )
    op.create_index(
        op.f("ix_pull_requests_pull_request_id"),
        "pull_requests",
        ["pull_request_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pull_requests_pull_request_id"), table_name="pull_requests")
    op.drop_table("pull_requests")
    op.drop_index(op.f("ix_users_user_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_teams_team_name"), table_name="teams")
    op.drop_table("teams")
    # ### end Alembic commands ###
